export const Products = [
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: ["/gamepad.png"],
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "AK-900 Wired Keyboard",
    price: 1160,
    imgSrc: ["/keyboard.png"],
    sales: 35,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "IPS LCD Gaming Monitor",
    price: 400,
    imgSrc: ["/monitor.png"],
    sales: 30,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "S-Series Comfort Chair",
    price: 400,
    imgSrc: ["/chair.png"],
    sales: 25,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: ["/gamepad.png"],
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: ["/gamepad.png"],
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: ["/gamepad.png"],
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: ["/gamepad.png"],
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
];
