export const OurProducts = [
  {
    name: "Breed Dry Dog Food",
    price: 100,
    imgSrc: "/dog-food.png",
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "CANON EOS DSLR Camera",
    price: 360,
    imgSrc: "/camera.png",
    rating: 3,
    reviewCount: 10,
  },
  {
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    imgSrc: "/laptop.png",
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "Curology Product Set ",
    price: 500,
    imgSrc: "/shamboo.png",
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "Kids Electric Car",
    price: 960,
    imgSrc: "/kids-car.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
    colors: ["red", "yellow"],
    new: true,
  },
  {
    name: "Jr. Zoom Soccer Cleats",
    price: 120,
    imgSrc: "/shoes.png",
    rating: 4,
    reviewCount: 10,
    colors: ["black", "gray"],
  },
  {
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    imgSrc: "/black-gamepad.png",
    rating: 4,
    reviewCount: 10,
    colors: ["red", "green"],
    new: true,
  },
  {
    name: "Quilted Satin Jacket",
    price: 660,
    imgSrc: "/jacket.png",
    rating: 4,
    reviewCount: 10,
    colors: ["orange", "yellow"],
  },
];
