export const OurProducts = [
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
    colors: ["red", "yellow"],
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
    colors: ["black", "gray"],
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
    colors: ["red", "green"],
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
    colors: ["orange", "yellow"],
  },
];
