export const Products = [
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
  {
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    imgSrc: "/gamepad.png",
    sales: 40,
    rating: 4,
    reviewCount: 10,
  },
];
